### ISSUE TITLE
is:issue is:open Okta authentication crashes, maybe okhttp library compatibility.

### ISSUE THREAD

**Issue by mcnarek** [okta/okta-auth-java#132]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [ ] bug report

### Background info

authenticationClient.authenticate(..) function call brings crash
please let me know what OKHTTP client version you are using.I think its about compatibility

Okta authentication call crashes
<img width="769" alt="Screen Shot 2022-02-22 at 18 05 36" src="https://user-images.githubusercontent.com/5946745/155148617-348bae95-2d5c-4825-884e-2139d3bc0cd2.png">
<img width="1123" alt="Screen Shot 2022-02-22 at 18 05 06" src="https://user-images.githubusercontent.com/5946745/155148641-9379c40b-162d-4219-9cfb-78fc357d08fa.png">

`Process: ai.scylla.mobilereporter, PID: 9196
    java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/Util;
        at com.okta.commons.http.okhttp.OkHttpRequestExecutor$InputStreamRequestBody.writeTo(OkHttpRequestExecutor.java:230)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:75)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
        at com.okta.commons.http.okhttp.OkHttpRequestExecutor.executeRequest(OkHttpRequestExecutor.java:164)
        at com.okta.commons.http.RetryRequestExecutor.doExecuteRequest(RetryRequestExecutor.java:147)
        at com.okta.commons.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:120)
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:469)
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$3$com-okta-sdk-impl-ds-DefaultDataStore(DefaultDataStore.java:343)
        at com.okta.sdk.impl.ds.DefaultDataStore$$ExternalSyntheticLambda2.filter(Unknown Source:8)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:375)
        at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:264)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:306)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:83)
        at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:74)
        at ai.scylla.authentication.okta.OktaAuthManagerImpl$authenticateUser$2.invokeSuspend(OktaAuthManagerImpl.kt:545)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Util" on path: DexPathList[[zip file "/data/app/~~6MYmHTIXKEfKgloVxwXjwg==/ai.scylla.mobilereporter-R9hTKzmgRZZ8D9yRC0pFeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~6MYmHTIXKEfKgloVxwXjwg==/ai.scylla.mobilereporter-R9hTKzmgRZZ8D9yRC0pFeg==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.okta.commons.http.okhttp.OkHttpRequestExecutor$InputStreamRequestBody.writeTo(OkHttpRequestExecutor.java:230) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:75) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) 
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158) 
        at com.okta.commons.http.okhttp.OkHttpRequestExecutor.executeRequest(OkHttpRequestExecutor.java:164) 
        at com.okta.commons.http.RetryRequestExecutor.doExecuteRequest(RetryRequestExecutor.java:147) 
        at com.okta.commons.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:120) 
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:469) 
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$3$com-okta-sdk-impl-ds-DefaultDataStore(DefaultDataStore.java:343) 
        at com.okta.sdk.impl.ds.DefaultDataStore$$ExternalSyntheticLambda2.filter(Unknown Source:8) 
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) 
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:375) 
        at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:264) 
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:306) 
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:83) 
        at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108) 
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:74) 
        at ai.scylla.authentication.okta.OktaAuthManagerImpl$authenticateUser$2.invokeSuspend(OktaAuthManagerImpl.kt:545) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
`

### SDK Version
<img width="480" alt="Screen Shot 2022-02-22 at 18 06 59" src="https://user-images.githubusercontent.com/5946745/155149374-2806d774-c08d-4cad-92d4-a4d4adc86ca3.png">

<img width="648" alt="Screen Shot 2022-02-22 at 18 10 54" src="https://user-images.githubusercontent.com/5946745/155149284-f48cc7b7-617a-4ab5-b9eb-4d74c79d6be6.png">

**Comment by JayNewstrom** [comment]
@arvindkrishnakumar-okta we're importing an internal class that's no longer available in the next version. I can post a PR to fix.

**Comment by JayNewstrom** [comment]
This isn't actually happening directly in okta-auth-java, but in a transitive dependency. I've made the fix here: https://github.com/okta/okta-commons-java/pull/72

**Comment by mcnarek** [comment]
Hi, so now what's the solution avoid this crash?
