### ISSUE TITLE
Failed resolution of: Ljava/time/format/DateTimeFormatter on Android 7 devices

### ISSUE THREAD

**Issue by thereallukesimpson** [okta/okta-auth-java#226]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

When updating SDK versions we noticed the appearance of a new crash originating in the Okta SDK (stack trace below). **It only impacts users on Android 7**.

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
       at com.okta.commons.http.RequestUtils.<clinit>(RequestUtils.java:32)
       at com.okta.commons.http.RequestUtils.fetchHeaderValueAndRemoveIfPresent(RequestUtils.java:93)
       at com.okta.commons.http.okhttp.OkHttpRequestExecutor.executeRequest(OkHttpRequestExecutor.java:122)
       at com.okta.commons.http.RetryRequestExecutor.doExecuteRequest(RetryRequestExecutor.java:147)
       at com.okta.commons.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:120)
       at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:442)
       at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$2(DefaultDataStore.java:316)
       at com.okta.sdk.impl.ds.DefaultDataStore.$r8$lambda$gKSDnks1-IbOCylz54X-TzaK5-s(DefaultDataStore.java)
       at com.okta.sdk.impl.ds.DefaultDataStore$$InternalSyntheticLambda$0$c4e7d458d0255d3533048628a92b18309bb945b5c716d564711e1a81e9edfaf4$0.filter(DefaultDataStore.java)
       at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
       at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:348)
       at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:246)
       at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:301)
       at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:83)
       at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108)
       at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:74)
```
### Expected behavior

No crash

### What went wrong?

Crash

### Steps to reproduce

Occurs for some users when logging in with username and password (`authenticationClient.authenticate(email, password, ...)`)

### SDK Version

Updated versions are:

implementation "com.okta.authn.sdk:okta-authn-sdk-api:2.0.2"
runtimeOnly "com.okta.authn.sdk:okta-authn-sdk-impl:2.0.2"
runtimeOnly "com.okta.authn.sdk:okta-authn-sdk-impl:2.02"
implementation "com.okta.android:okta-oidc-android:1.3.2"
runtimeOnly "com.okta.sdk:okta-sdk-okhttp:8.2.1"

Previous versions were:

implementation "com.okta.authn.sdk:okta-authn-sdk-api:2.0.0"
runtimeOnly "com.okta.authn.sdk:okta-authn-sdk-impl:2.0.0"
runtimeOnly "com.okta.authn.sdk:okta-authn-sdk-impl:2.0.0"
implementation "com.okta.android:okta-oidc-android:1.2.2"
runtimeOnly "com.okta.sdk:okta-sdk-okhttp:2.0.0"

**Comment by arvindkrishnakumar-okta** [comment]
`java.time.format.DateTimeFormatter` is available only from Java 8 onwards. Please ensure you use this SDK with Java 8+.

**Comment by thereallukesimpson** [comment]
Thanks, @arvindkrishnakumar-okta but we are using Java 11:

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
```

**Comment by bdemers** [comment]
@thereallukesimpson 
Older versions of Android do not support all of the Java 8 APIs:
https://developer.android.com/studio/write/java8-support-table

There are options to add a "desugar" library/build step to your build if you need to support those versions of android.
https://developer.android.com/studio/write/java8-support#library-desugaring

Be warned, that version of Android is EOL (End of Life) and is no longer receiving security updates.
> It's not possible to build a secure app on top of an insecure system.

**Comment by thereallukesimpson** [comment]
Hi @bdemers. Thanks for the response. Can you add a minSdk to this library so we discover this at compile time rather than when it starts to crash in production?

**Comment by bdemers** [comment]
Is there a metadata file that the Android build tools will read to throw a warning?  If so we could probably do that.

it’s potential also a fuzzy min version, if you are using a de-sugaring technique.
