### ISSUE TITLE
Getting NoClassDefFound for BaseClient.java while using okta-authn-sdk-api:2.0.9 with okta-sdk-api:10.0.0

### ISSUE THREAD

**Issue by sunilchaurha** [okta/okta-auth-java#255]
When I use okta-sdk-api:10.0.0 with okta-authn-sdk-api:2.0.9, It's failing to create AuthenticationClient object due to missing BaseClient class in okta-sdk-api:10.0.0.

Stacktrace: 
java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.okta.authn.sdk.impl.client.DefaultAuthenticationClientBuilder.build(DefaultAuthenticationClientBuilder.java:212)

**Comment by Marek26** [comment]
Any update on that issue?

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for the enhancement request to this repository. With Okta’s release of Identity Engine, we are minimizing the investment in this SDK that works with our Classic Engine. Maintenance of this repository with be limited to fixing critical bugs and security vulnerabilities.

**Comment by Marek26** [comment]
This would force us to use a retired version of https://github.com/okta/okta-sdk-java which I see as a potential security vulnerability.

Not adding new features is absolutely fine, but KTLO efforts should still be considered to run this SDK in a safely manner.

**Comment by arvindkrishnakumar-okta** [comment]
@Marek26 we'd still plan to address critical sec vulnerabilities to retired okta-sdk-java version.
