### ISSUE TITLE
Simple example with Clients.builder() doesn't  work

### ISSUE THREAD

**Issue by seregasheypak** [okta/okta-auth-java#49]
dependencies:
```
 compile group: 'com.okta.authn.sdk', name: 'okta-authn-sdk-api', version: "1.0.0"
    runtime group: 'com.okta.authn.sdk', name: 'okta-authn-sdk-impl', version: "1.0.0"
    runtime group: 'com.okta.sdk', name: 'okta-sdk-httpclient', version: '1.5.2'
```

code
```scala
val client = Clients.builder()
    .setOrgUrl(oktaDomain)
    .setClientCredentials(new TokenClientCredentials(apiToken))
    .build()
```

exception
```
Exception in thread "main" java.lang.IllegalStateException: Unable to find a 'com.okta.sdk.impl.http.RequestExecutorFactory' implementation on the classpath.  Please ensure you have added the okta-sdk-httpclient.jar file to your runtime classpath.
	at com.okta.commons.lang.Classes.lambda$loadFromService$0(Classes.java:205)
	at com.okta.commons.lang.Classes$$Lambda$19/431687835.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.okta.commons.lang.Classes.loadFromService(Classes.java:205)
	at com.okta.sdk.impl.client.BaseClient.createRequestExecutor(BaseClient.java:103)
	at com.okta.sdk.impl.client.BaseClient.<init>(BaseClient.java:72)
	at com.okta.sdk.impl.client.AbstractClient.<init>(AbstractClient.java:60)
	at com.okta.sdk.impl.client.DefaultClient.<init>(DefaultClient.java:117)
	at com.okta.sdk.impl.client.DefaultClientBuilder.build(DefaultClientBuilder.java:322)
	at OktaSample$.delayedEndpoint$com$parity$OktaSample$1(OktaSample.scala:17)

```

**Comment by seregasheypak** [comment]
Seems like caused by messy deps
It "works" with these dependencies
```
    implementation group: 'com.okta.sdk', name: 'okta-sdk-api', version: "1.5.2"
    implementation group: 'com.okta.sdk', name: 'okta-sdk-impl', version: "1.5.2"
    implementation group: 'com.okta.sdk', name: 'okta-sdk-httpclient', version: '1.5.2'
```

**Comment by bdemers** [comment]
Thanks again! I'm correcting the gradle deps in the Readme!
