### ISSUE TITLE
com.okta.sdk.impl.ds.MarshalingException: Unable to convert InputStream String to Map

### ISSUE THREAD

**Issue by seregasheypak** [okta/okta-auth-java#50]
```scala
val client = Clients.builder()
    .setOrgUrl(oktaDomain)
    .setClientCredentials(new TokenClientCredentials(apiToken))
    .build()

  client.listUsers().asScala.foreach{ u =>
    println(s"user: $u")
  }
```

`client.listUsers()`

throws exception

```
Exception in thread "main" com.okta.sdk.impl.ds.MarshalingException: Unable to convert InputStream String to Map.
	at com.okta.sdk.impl.ds.JacksonMapMarshaller.unmarshal(JacksonMapMarshaller.java:100)
	at com.okta.sdk.impl.ds.DefaultDataStore.getBody(DefaultDataStore.java:466)
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:443)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$0(DefaultDataStore.java:193)
	at com.okta.sdk.impl.ds.DefaultDataStore$$Lambda$34/891093184.filter(Unknown Source)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:205)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:174)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:169)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:165)
	at com.okta.sdk.impl.client.DefaultClient.listUsers(DefaultClient.java:793)
	at OktaSample$.delayedEndpoint$com$parity$OktaSample$1(OktaSample.scala:20)
	at OktaSample$delayedInit$body.apply(OktaSample.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.App$$Lambda$5/1908153060.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at OktaSample$.main(OktaSample.scala:9)
	at OktaSample.main(OktaSample.scala)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (ByteArrayInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2630)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at com.okta.sdk.impl
```
I suspect bad token or url, and it would be great to propagate proper exception.

**Comment by bdemers** [comment]
Can you double check your Okta domain, and token.  What is your Okta domain?

Either way we should catch this error and include it on the Exception.

**Comment by seregasheypak** [comment]
`What is your Okta domain `

I'm new to it and I've created developer account. Where can I find my "okta domain" Which part of Admin Console?
Could you point me please?

**Comment by bdemers** [comment]
Thanks for the clarification! We should be able to add a check for that and provide a better exception message for related cases. 
I’m guessing you are no the only one who has seen this.

**Comment by seregasheypak** [comment]
my bad, gradle wasn't able to access jdk cacerts. I had to trace IDE logs to find it, sorry!
