### ISSUE TITLE
Cannot get basic example to work

### ISSUE THREAD

**Issue by yashrao99** [okta/okta-auth-java#52]
Here are my deps in gradle 

```groovy
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    runtimeOnly 'com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0'
    runtimeOnly 'com.okta.sdk:okta-sdk-okhttp:1.5.2'
````

and my code

```groovy
val mOktaAuth = AuthenticationClients.builder().setOrgUrl("https://app-api.okta.com").build()

mOktaAuth.authenticate(emailText.text.toString(), passwordText.text.toString().toCharArray(), "/application/specific", x)

x being my AuthenticationStateHandlerAdapter
```

```groovy
and the error I get every time is 
`com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: null`
```

**Comment by yashrao99** [comment]
Also, if I use my dependencies as

```groovy
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    runtimeOnly 'com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0'
    runtimeOnly 'com.okta.sdk:okta-sdk-httpclient:1.5.2'
```
I get a crash at `val mOktaAuth = AuthenticationClients.builder().setOrgUrl("https://mydomain").build()`

The crash being:
```groovy
    java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
```

**Comment by bdemers** [comment]
Hey @yashrao99 !

On Android you should use ‘okta-sdk-okhttp’ instead of ‘okta-sdk-httpclient’ (Because of a dead version of httpclient on Android)

Do you have a stacktrace when using okhttp?

**Comment by yashrao99** [comment]
Hey @bdemers , Thanks for the quick response, really appreciate it. 

Here is the full stack trace
```groovy
2019-06-13 08:30:39.098 15356-15356/com.suki.suki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.suki.suki, PID: 15356
    com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: null
        at com.okta.sdk.impl.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:141)
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:435)
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1$DefaultDataStore(DefaultDataStore.java:314)
        at com.okta.sdk.impl.ds.-$$Lambda$DefaultDataStore$fo-umUTYx0eD5hn0AHqFzrmI4sg.filter(Unknown Source:8)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:346)
        at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:244)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:324)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:106)
        at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:97)
        at com.suki.suki.LoginActivity$onCreate$1.onClick(LoginActivity.kt:57)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
        at java.net.InetAddress.getAllByName(InetAddress.java:1154)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.okta.sdk.impl.http.okhttp.OkHttpRequestExecutor.executeRequest(OkHttpRequestExecutor.java:144)
2019-06-13 08:30:39.098 15356-15356/com.suki.suki E/AndroidRuntime:     at com.okta.sdk.impl.http.RetryRequestExecutor.doExecuteRequest(RetryRequestExecutor.java:149)
        at com.okta.sdk.impl.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:123)
        	... 22 more
```

I went into the okta-java-sdk and I see where the exception is being raised but not sure what I'm doing wrong

**Comment by bdemers** [comment]
Looks like Android is blocking that DNS request.  Did you include the "internet" permission?

Similar to this:
https://github.com/okta/samples-android/blob/master/browser-sign-in/app/src/main/AndroidManifest.xml#L17

**Comment by yashrao99** [comment]
@bdemers I have. Do you think it's possibly because I'm using the emulator? Not sure what else there is to change

**Comment by yashrao99** [comment]
```groovy
2019-06-13 10:36:11.993 16498-16498/com.suki.suki E/InputEventSender: Exception dispatching finished signal.
2019-06-13 10:36:11.993 16498-16498/com.suki.suki E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2019-06-13 10:36:12.001 16498-16498/com.suki.suki E/MessageQueue-JNI: com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: null
        at com.okta.sdk.impl.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:141)
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:435)
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1$DefaultDataStore(DefaultDataStore.java:314)
        at com.okta.sdk.impl.ds.-$$Lambda$DefaultDataStore$fo-umUTYx0eD5hn0AHqFzrmI4sg.filter(Unknown Source:8)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:346)
        at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:244)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:324)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:106)
        at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:97)
        at com.suki.suki.LoginActivity$onCreate$1.onClick(LoginActivity.kt:57)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.onKeyUp(View.java:13216)
        at android.widget.TextView.onKeyUp(TextView.java:7821)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2716)
        at android.view.View.dispatchKeyEvent(View.java:12450)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3360)
        at android.support.v4.app.SupportActivity.superDispatchKeyEvent(ComponentActivity.java:108)
        at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5037)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4905)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4618)
    	at android.view.ViewR
2019-06-13 10:36:12.001 16498-16498/com.suki.suki D/AndroidRuntime: Shutting down VM
2019-06-13 10:36:12.003 16498-16498/com.suki.suki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.suki.suki, PID: 16498
    com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: null
        at com.okta.sdk.impl.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:141)
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:435)
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1$DefaultDataStore(DefaultDataStore.java:314)
        at com.okta.sdk.impl.ds.-$$Lambda$DefaultDataStore$fo-umUTYx0eD5hn0AHqFzrmI4sg.filter(Unknown Source:8)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:346)
        at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:244)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:324)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:106)
        at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:97)
        at com.suki.suki.LoginActivity$onCreate$1.onClick(LoginActivity.kt:57)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.onKeyUp(View.java:13216)
        at android.widget.TextView.onKeyUp(TextView.java:7821)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2716)
        at android.view.View.dispatchKeyEvent(View.java:12450)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3360)
        at android.support.v4.app.SupportActivity.superDispatchKeyEvent(ComponentActivity.java:108)
        at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5037)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4905)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
2019-06-13 10:36:12.004 16498-16498/com.suki.suki E/AndroidRuntime:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4618)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4779)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
        at java.net.InetAddress.getAllByName(InetAddress.java:1154)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.okta.sdk.impl.http.okhttp.OkHttpRequestExecutor.executeRequest(OkHttpRequestExecutor.java:144)
        at com.okta.sdk.impl.http.RetryRequestExecutor.doExecuteRequest(RetryRequestExecutor.java:149)
        at com.okta.sdk.impl.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:123)
```

Made it a little further by configuring emulator settings? Not sure if that was a step forward or not

**Comment by bdemers** [comment]
Does your browse or other network connections work in your emulator?

**Comment by yashrao99** [comment]
Yeah the browser/other connections are fine

**Comment by FeiChen-okta** [comment]
Hi @yashrao99,

The issue is caused by android.os.NetworkOnMainThreadException
Which means your app is probably calling the the AuthenticationClient's networking API on the uiThread. Try using a AsyncTask or executor service to see if that helps.

**Comment by yashrao99** [comment]
@FeiChen-okta  wow.. can't believe that was the issue. Thank you so much
