### ISSUE TITLE
HTTP 405, Okta E0000022

### ISSUE THREAD

**Issue by alexzaitsev** [okta/okta-auth-java#61]
Hello, I'm implementing native sign-in on Android using [this example](https://github.com/okta/okta-oidc-android/blob/master/app/src/main/java/com/okta/oidc/example/SampleActivity.java) from [Okta OIDC Android](https://github.com/okta/okta-oidc-android) repository.
I'm calling this method from the background thread:
```
GlobalScope.launch(IO) {
                authenticationClient.authenticate(
                    login, password.toCharArray(), null,
                    sessionTokenCallback
                )
            }
```
and got the next error:
```
2020-03-18 16:44:43.046 21568-21671/com.mypackname.nsp E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.mypackname.nsp, PID: 21568
    com.okta.sdk.resource.ResourceException: HTTP 405, Okta E0000022 (The endpoint does not support the provided HTTP method), ErrorId oaeMPidYiw9RSSSLI9nohkI4A
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:453)
        at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1$DefaultDataStore(DefaultDataStore.java:314)
        at com.okta.sdk.impl.ds.-$$Lambda$DefaultDataStore$fo-umUTYx0eD5hn0AHqFzrmI4sg.filter(Unknown Source:8)
        at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
        at com.okta.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:346)
        at com.okta.sdk.impl.ds.DefaultDataStore.create(DefaultDataStore.java:244)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.doPost(DefaultAuthenticationClient.java:324)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:106)
        at com.okta.authn.sdk.client.AuthenticationClient.authenticate(AuthenticationClient.java:108)
        at com.okta.authn.sdk.impl.client.DefaultAuthenticationClient.authenticate(DefaultAuthenticationClient.java:97)
        at com.mypackname.nsp.view.auth.AuthViewModel$login$1.invokeSuspend(AuthViewModel.kt:148)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2020-03-18 16:44:43.084 21568-21671/com.mypackname.nsp I/Process: Sending signal. PID: 21568 SIG: 9
```

Do you have any ideas why I get 405 error?

**Comment by bdemers** [comment]
Hey @alexzaitsev!

Usually, this means your base URL is incorrect (but was a valid URL), maybe the path in the URL is wrong?  If you cannot figure it out, you can share it here (or if you want to keep it private) email Developer support: `developers at okta.com`, and include a link to this thread.

**Comment by alexzaitsev** [comment]
@bdemers thanks, seems that I managed to fix it using your answer. Now I get "MFA_REQUIRED".... 
If you have any idea where to dig further - please give me a link / whatever.
I'm closing this issue, thanks a lot!

**Comment by bdemers** [comment]
cc @FeiChen-okta do you have a MFA example handy?

**Comment by FeiChen-okta** [comment]
@alexzaitsev Yes you can handle the MFA by using the state handler or simply checking the status. A simple example that only handles push/question/totp factors:
```java
public AuthenticationResponse verifyFactor(final AuthenticationResponse response,
                                               final FactorType type,
                                               final String totpOrAnswer)
            throws AuthenticationException {
        String stateToken = response.getStateToken();
        Factor factor = getFactorByType(response.getFactors(), type);
        VerifyFactorRequest request;
        if (type == PUSH) {
            request = authenticationClient.instantiate(VerifyPushFactorRequest.class);
        } else {
            // For TOTP or QUESTION.
            request = authenticationClient.instantiate(VerifyFactorRequest.class);
            request.put(type == TOKEN_SOFTWARE_TOTP ? "passCode" : "answer", totpOrAnswer);
        }
        request.setStateToken(stateToken);
        return authenticationClient.verifyFactor(factor.getId(), request, null);
    }
```

The method returns a AuthenticatorResponse that should have a SUCCESS status.
If the factor is push then get the factor status and it should be WAITING. which means it is waiting for the user to accept the push notification.
